### ISSUE TITLE
Incorrect .cfg syntax highlight.

### ISSUE THREAD

**Issue by cpud36** [nim-lang/NimLime#56]
In file https://github.com/nim-lang/Nim/blob/devel/config/nim.cfg#L135. It does not detect key-value pair and highlights huge section after it as string.

``` nim
  gcc.options.linker %= "-L $WIND_BASE/target/lib/usr/lib/ppc/PPC32/common -mrtp -fno-strict-aliasing -D_C99 -D_HAS_C9X -std=c99 -fasm -Wall -Wno-write-strings"
```

I suppose that problem is because  '%=' instead of '='. I checked the source of **parsecfg**. '%=' means nothing.

**Comment by onionhammer** [comment]
the preceding operator shouldn't matter; a string is a string.

**Comment by cpud36** [comment]
It shouldn't, but it do. It does not highlight a string as a string,  but it highlights a huge part of file as a string.
https://github.com/Varriount/NimLime/blob/master/Syntaxes/Nim_Cfg.YAML-tmLanguage#L28
```yaml
- comment: Key declarations
  begin: ([a-zA-Z0-9_\.]+)\s*(\=)
  end: \n
  patterns:
# ...
  - comment: Double Quoted String
    name: string.quoted.double.nimcfg
    begin: \"
    end: \"
    captures:
      '1': {name: storage.type.function.nimcfg}
    patterns:
    - match: (\\([abenrclftv\\]|["']|[0-9])|x\h\h)
```
According to this, it does not detect a string if key-value separator isn't '='. But it should.
